[language-server]
typos-lsp = { command = "typos-lsp" }
# tinymist = { command = "tinymist" }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }
language-servers = ["taplo", "typos-lsp"]

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = false

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "typst"
auto-format = true
# formatter = { command = "typstfmt", args = ["--output", "-"] }
language-servers = ["tinymist", "typos-lsp"]

[[language]]
name = "markdown"
language-servers = ["marksman", "typos-lsp"]

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer", "typos-lsp"]

[[language]]
name = "sql"
file-types = ["sql"]
formatter = { command = "sqlfluff", args = ["format"] }

[[language]]
name = "yaml"
file-types = ["yml", "yaml"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }
language-servers = ["yaml-language-server"]

[[language]]
name = "python"
auto-format = true
language-servers = ["ty", "ruff", "typos-lsp"]
